language: python
sudo: true
dist: bionic

branches:
  only:
  - master
  - v*
  
python:
# - 3.4 Not in travis repositories
#- 3.5 Not in travis repositories
- 3.6
- 3.7
- 3.8

addons:
  apt:
    packages:
    - pandoc

before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda3/bin:$PATH
- ls
- conda update --yes conda
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose matplotlib numba
- pip install codecov pypandoc
- python setup.py install
script:
- nosetests --verbosity=3 --with-coverage --cover-package=aotools test/
after_success:
- codecov
#deploy:
#  provider: pypi
#
#  user: "andrewpaulreeves"
#  skip_upload_docs: true
#  password:
#    secure: zPqU18TzdjuzrnrzmQtSzrWOpF4r1HB9MOrgS9YttmbNh8itZ2BPrWGBAtzHPhti4elh4hwkdUH7lHqbuDOPK7E7+Qik7rQtNWZdzQqO1jjeY9eC3l0H7tvQtPLAErFYbgF9ZCwFIqN/MXt2WEHHirRNe+4f9tqxqnCEabOO+VAHE6ktHyYtkcCKibbmvSj9IHJw0r8rbtlOQA5aGL0VB+tJwkitpJsre76PacBFMi8Q77PkoDdItLK+622IPRwJBFKzwmvypR9MM9wrOZjSKbsS7uDVCMeVzbal9EpVV4FM1opCyvaRerLyC68+e/ilJdZK5GxbPKS84Fxbr4Bvq8n1uoNguNF2ldo9xznSlR3Izd1d9ena0QlNCNFxoVO/SdpENI5Q1gRecxoNdKPLBAtnuw732wvzSP29eY+u500T0aaBbh6n71WoswT1IcbRWeXDFXGuOwDm6NUilwWKa1U+8+tUJg76SWmOsPkGmFNQDmtJVP+7xfIgBfu+ThC89ymvNdtkEWI7USUPSifW6vnRmfaNVzts3PGXZv/LsaEd4p9ebM/RFNaQtGfWVBpqGRDMiL0AHv73Z/RxQZ/sl6PAmctkjtOhYdd5GErkkK8GTPFw9kdm+7HbNfund1tHyn3WE4ccC7rp4jJEJZQxAAN0nGmnfZBStA/UJuNX2t0=
